LABEL_LIST = [
    "airplane",
    "angel",
    "ant",
    "apple",
    "axe",
    "bathtub",
    "beach",
    "bee",
    "bicycle",
    "birthday cake",
    "book",
    "bus",
    "butterfly",
    "calculator",
    "camel",
    "castle",
    "cat",
    "cow",
    "crab",
    "crocodile",
    "diamond",
    "elephant",
    "eye",
    "frying pan",
    "giraffe",
    "hammer",
    "hand",
    "helicopter",
    "horse",
    "hospital",
    "key",
    "lightning",
    "mermaid",
    "mountain",
    "ocean",
    "palm tree",
    "piano",
    "pineapple",
    "pizza",
    "police car",
    "screwdriver",
    "sheep",
    "snail",
    "suitcase",
    "tractor",
    "watermelon",
    "wheel",
    "wristwatch",
]
