
name: Debug unit tests

# Run the workflow on every pull-request
on:
  push:
    branches: 
      - feature/test-actions

jobs:
  run-linter:
   name: Run linter
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout out git repo
      uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: pip install flake8

    - name: Run linter
      run: flake8

  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    
 
    steps:
    - name: Check out git repo
      uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests
      shell: bash
      run: python src/runTests.py --keys='${{ fromJSON(secrets.TEST_SETTINGS) }}'
