# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - tekniskback

on:
  push:
    branches:
      - master

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out git repo
      uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: pip install flake8

    - name: Run linter
      run: flake8

  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out git repo
      uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests
      run: pytest --ignore=machine_learning_utilities
      

  build-and-deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    # Need to create credentials
    # - name: 'Azure Login'
      # uses: azure/login@v1.1
      # with:
        # creds: '${{ secrets.AZURE_CREDENTIALS }}' 

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
      
    - name: 'Run pip'
      shell: bash
      run: |
        # If your web app project is not located in your repository's root
        # Please change your directory for pip in pushd
        pushd .
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/python3.7/site-packages"
        popd

    - name: Build using AppService-Build
      uses: azure/appservice-build@v1
      with:
        platform: python
        platform-version: '3.7'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'tekniskback'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a896db61b89543ea8da604e9a364cedd }}
        
    # Login needed for this to work
    # - name: Azure App Service Settings
      # uses: Azure/appservice-settings@v1
      # with:
        # app-name: 'tekniskback'
        # Application settings using the JSON syntax set as value of secret variable: APP_SETTINGS
        # app-settings-json: '${{ secrets.APP_SETTINGS }}'
        # Connection Strings using the JSON syntax set as value of secret variable: CONNECTION_STRINGS
        # connection-strings-json: # optional
        # General configuration settings using dictionary syntax - Key Value pairs
        # general-settings-json: # optional
