
name: Lint and test pull-request - tekniskback

# Run the workflow on every pull-request
on:
  pull_request:

jobs:
  run-linter:
   name: Run linter
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout out git repo
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install flake8

    - name: Run linter
      run: flake8

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests
      run: pytest
