
name: Lint and test pull-request - tekniskback

# Run the workflow on every pull-request
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  run-linter:
   name: Run linter
   runs-on: ubuntu-22.04
   env: 
    TESTING: "true"
    IS_PRODUCTION: "false"
   
   steps:
    - name: Checkout out git repo
      uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install flake8

    - name: Run linter
      run: flake8

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      shell: bash
      run: python3 src/runTests.py --keys='${{ secrets.NEW_TEST_SETTINGS }}'
      
